const nodes_b2c = [

    {
        id: "rolling",
        label: "rolling",
        type: "rolling",
        position: { x: -107, y: 120 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Right",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "workflow",
        label: "Work flow",
        type: "workflow",
        position: { x: 0 , y: 310 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "pm",
        label: "pm",
        type: "pm",
        position: { x: 0, y: 170 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "budget",
        label: "budget",
        type: "budget",
        position: { x: 0, y: 120 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },

    {
        id: "pmprice",
        label: "pm price",
        type: "pmprice",
        position: { x: 40, y: 270 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },

    {
        id: "volume",
        label: "材積",
        type: "volume",
        position: { x: 40, y: 220 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "DCM",
        label: "DCM",
        type: "DCM",
        position: { x: -134, y: 170 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "rollingorder",
        label: "接單",
        type: "rollingorder",
        position: { x: -138, y: 220 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "rolling2",
        label: "Rolling",
        type: "rolling2",
        position: { x: -160, y: 270 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "nucleation",
        label: "核配",
        type: "nucleation",
        position: { x: -138, y: 320 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "addorder",
        label: "加單",
        type: "addorder",
        position: { x: -138, y: 370 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "proposal",
        label: "Proposal",
        type: "proposal",
        position: { x: -54, y: 360 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Right",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "epayment",
        label: "E-payment",
        type: "epayment",
        position: { x: 60, y: 360 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "ecredit",
        label: "E-credit",
        type: "ecredit",
        position: { x: -56, y: 410 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#11a0c4",
            color: "#11a0c4",
            linearStartColor: "#11a0c4",
            linearEndColor: "#11a0c4",
            hoverBorderColor: "#11a0c4",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
];

const edges_b2c = [
    {
        id: "B2C-rolling",
        source: "B2C",
        target: "rolling",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "B2C-workflow",
        source: "B2C",
        target: "workflow",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "B2C-pm",
        source: "B2C",
        target: "pm",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "B2C-budget",
        source: "B2C",
        target: "budget",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "pm-pmprice",
        source: "pm",
        target: "pmprice",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "pm-volume",
        source: "pm",
        target: "volume",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "rolling-DCM",
        source: "rolling",
        target: "DCM",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "rolling-rollingorder",
        source: "rolling",
        target: "rollingorder",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "rolling-rolling2",
        source: "rolling",
        target: "rolling2",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "rolling-nucleation",
        source: "rolling",
        target: "nucleation",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "rolling-addorder",
        source: "rolling",
        target: "addorder",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "workflow-proposal",
        source: "workflow",
        target: "proposal",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "workflow-epayment",
        source: "workflow",
        target: "epayment",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "workflow-ecredit",
        source: "workflow",
        target: "ecredit",
        style: { stroke: "#11a0c4" },
        hidden: false,
        type: "smoothstep",
    },
]

export { nodes_b2c, edges_b2c }