const nodes_sales = [

    {
        id: "crm",
        label: "CRM",
        type: "crm",
        position: { x: 160, y: -50 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#8585d6",
            color: "#8585d6",
            linearStartColor: "#8585d6",
            linearEndColor: "#8585d6",
            hoverBorderColor: "#8585d6",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "app",
        label: "APP",
        type: "app",
        position: { x: 240, y: -50 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#8585d6",
            color: "#8585d6",
            linearStartColor: "#8585d6",
            linearEndColor: "#8585d6",
            hoverBorderColor: "#8585d6",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "order",
        label: "order",
        type: "order",
        position: { x: 160, y:320 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#8585d6",
            color: "#8585d6",
            linearStartColor: "#8585d6",
            linearEndColor: "#8585d6",
            hoverBorderColor: "#8585d6",
            hoverColor: "#fff",
            source: "Bottom",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "esign",
        label: "E-Sign",
        type: "esign",
        position: { x: 180, y: -100 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#8585d6",
            color: "#8585d6",
            linearStartColor: "#8585d6",
            linearEndColor: "#8585d6",
            hoverBorderColor: "#8585d6",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "customerprofile",
        label: "Customer Profile",
        type: "customerprofile",
        position: { x: 114, y: -150 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#8585d6",
            color: "#8585d6",
            linearStartColor: "#8585d6",
            linearEndColor: "#8585d6",
            hoverBorderColor: "#8585d6",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
];

const edges_sales = [
    {
        id: "SALES-crm",
        source: "SALES",
        target: "crm",
        style: { stroke: "#8585d6" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "SALES-app",
        source: "SALES",
        target: "app",
        style: { stroke: "#8585d6" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "app-esign",
        source: "app",
        target: "esign",
        style: { stroke: "#8585d6" },
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "app-customerprofile",
        source: "app",
        target: "customerprofile",
        style: { stroke: "#8585d6" },
        hidden: false,
        type: "smoothstep",
    },
]

export { nodes_sales, edges_sales }