const nodes_aorus = [

    {
        id: "AORUS2.0",
        label: "AORUS 2.0",
        type: "aorus2.0",
        position: { x: 400, y: -120 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "Member",
        label: "會員系統",
        type: "member",
        position: { x: 470, y: -145 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Top",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "productregister",
        label: "產品註冊",
        type: "productregister",
        position: { x: 470, y: -195 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "productpageseo",
        label: "Product Page SEO",
        type: "productpageseo",
        position: { x: 320, y: -270 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "EC",
        label: "EC",
        type: "EC",
        position: { x: 320, y: -320 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "Gamebundle",
        label: "Gamebundle",
        type: "gamebundle",
        position: { x: 320, y: -170 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "Wallpaper",
        label: "Wallpaper",
        type: "wallpaper",
        position: { x: 320, y: -220 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "cms",
        label: "CMS",
        type: "cms",
        position: { x: 470, y: -245 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "autotrans",
        label: "自動翻譯",
        type: "autotrans",
        position: { x: 470, y: -295 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "gbtru",
        label: "GIGABYTE RU",
        type: "gbtru",
        position: { x: 470, y: -345 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "invoiceAi",
        label: "Invoice Ai",
        type: "invoiceAi",
        position: { x: 570, y: -170 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Top",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "warranty",
        label: "Warranty",
        type: "warranty",
        position: { x: 570, y: -220 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
    {
        id: "repair",
        label: "自動送修",
        type: "repair",
        position: { x: 570, y: -270 },
        data: {
            backgroundColor: "#fff",
            borderColor: "#ff6400",
            color: "#ff6400",
            linearStartColor: "#ff6400",
            linearEndColor: "#ff6400",
            hoverBorderColor: "#ff6400",
            hoverColor: "#fff",
            source: "Right",
            target: "Left",
            style: {
                width: "auto",
            },
        },
        style: {
            animation: "openIn 0.5s ease-in-out",
        },
        nodeType: 'child',
        hidden: true,
    },
];

const edges_aorus = [
    {
        id: "AORUS-AORUS2.0",
        source: "AORUS",
        target: "AORUS2.0",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-Member",
        source: "AORUS",
        target: "Member",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-productregister",
        source: "AORUS",
        target: "productregister",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-productpageseo",
        source: "AORUS",
        target: "productpageseo",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-EC",
        source: "AORUS",
        target: "EC",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-Gamebundle",
        source: "AORUS",
        target: "Gamebundle",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-Wallpaper",
        source: "AORUS",
        target: "Wallpaper",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-cms",
        source: "AORUS",
        target: "cms",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-autotrans",
        source: "AORUS",
        target: "autotrans",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "AORUS-gbtru",
        source: "AORUS",
        target: "gbtru",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "productregister-invoiceAi",
        source: "productregister",
        target: "invoiceAi",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "productregister-warranty",
        source: "productregister",
        target: "warranty",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "productregister-repair",
        source: "productregister",
        target: "repair",
        style: { stroke: "#ff6400" },
        // animated: true,
        hidden: false,
        type: "smoothstep",
    },
    {
        id: "invoiceAi-BI",
        source: "invoiceAi",
        target: "BI",
        style: { stroke: "#ccc" },
        animated: true,
        hidden: false,
        // type: "smoothstep",
    },

    
    {
        id: "Member-crm",
        source: "Member",
        target: "crm",
        style: { stroke: "#ccc" },
        animated: true,
        hidden: false,
        // type: "smoothstep",
    },
    
    {
        id: "productregister-crm",
        source: "productregister",
        target: "crm",
        style: { stroke: "#ccc" },
        animated: true,
        hidden: false,
        // type: "smoothstep",
    },
]

export { nodes_aorus, edges_aorus }